// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Components__AppController from "./components/app_controller.js"
application.register("components--app", Components__AppController)

import Components__Base__NavigationController from "./components/base/navigation_controller.js"
application.register("components--base--navigation", Components__Base__NavigationController)

import Components__Base__TurboModalController from "./components/base/turbo_modal_controller.js"
application.register("components--base--turbo-modal", Components__Base__TurboModalController)

import Components__BlockUiController from "./components/block_ui_controller.js"
application.register("components--block-ui", Components__BlockUiController)

import Components__DialerController from "./components/dialer_controller.js"
application.register("components--dialer", Components__DialerController)

import Components__DrawerController from "./components/drawer_controller.js"
application.register("components--drawer", Components__DrawerController)

import Components__ImageInputController from "./components/image_input_controller.js"
application.register("components--image-input", Components__ImageInputController)

import Components__MenuController from "./components/menu_controller.js"
application.register("components--menu", Components__MenuController)

import Components__PasswordMeterController from "./components/password_meter_controller.js"
application.register("components--password-meter", Components__PasswordMeterController)

import Components__ScrollController from "./components/scroll_controller.js"
application.register("components--scroll", Components__ScrollController)

import Components__ScrolltopController from "./components/scrolltop_controller.js"
application.register("components--scrolltop", Components__ScrolltopController)

import Components__SearchController from "./components/search_controller.js"
application.register("components--search", Components__SearchController)

import Components__StepperController from "./components/stepper_controller.js"
application.register("components--stepper", Components__StepperController)

import Components__StickyController from "./components/sticky_controller.js"
application.register("components--sticky", Components__StickyController)

import Components__SwapperController from "./components/swapper_controller.js"
application.register("components--swapper", Components__SwapperController)

import Components__ToggleController from "./components/toggle_controller.js"
application.register("components--toggle", Components__ToggleController)

import Components__TooltipController from "./components/tooltip_controller.js"
application.register("components--tooltip", Components__TooltipController)

import Devise__ApplicationController from "./devise/application_controller.js"
application.register("devise--application", Devise__ApplicationController)

import Devise__Confirmations__NewController from "./devise/confirmations/new_controller.js"
application.register("devise--confirmations--new", Devise__Confirmations__NewController)

import Devise__Passwords__EditController from "./devise/passwords/edit_controller.js"
application.register("devise--passwords--edit", Devise__Passwords__EditController)

import Devise__Passwords__NewController from "./devise/passwords/new_controller.js"
application.register("devise--passwords--new", Devise__Passwords__NewController)

import Devise__Registrations__NewController from "./devise/registrations/new_controller.js"
application.register("devise--registrations--new", Devise__Registrations__NewController)

import Devise__Sessions__NewController from "./devise/sessions/new_controller.js"
application.register("devise--sessions--new", Devise__Sessions__NewController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import Utils__ConfirmController from "./utils/confirm_controller.js"
application.register("utils--confirm", Utils__ConfirmController)

import Utils__ConfirmSwalController from "./utils/confirm_swal_controller.js"
application.register("utils--confirm-swal", Utils__ConfirmSwalController)

import Utils__Forms__ErrorsController from "./utils/forms/errors_controller.js"
application.register("utils--forms--errors", Utils__Forms__ErrorsController)

import Utils__Forms__SearchController from "./utils/forms/search_controller.js"
application.register("utils--forms--search", Utils__Forms__SearchController)
